### ISSUE TITLE
Problem with initial setup for existing project

### ISSUE THREAD

**Issue by SalahAdDin** [skirsdeda/wagtail-translation#3]
Hi, i'm testing your package and i haven't problem with it, at least until run it.

Trying to run it i get tow problems:
First in the first pages:

The second is editting whatever web page that i want translate:
```
TypeError at /admin/pages/5/edit/
'title_es' is an invalid keyword argument for this function
```
 This is his traceback:
 ```
 Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail/wagtailadmin/decorators.py", line 24, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail/wagtailadmin/views/home.py", line 101, in home
    'user': request.user
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 1044, in render
    output = self.filter_expression.resolve(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 711, in resolve
    obj = self.var.resolve(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 852, in resolve
    value = self._resolve_lookup(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 915, in _resolve_lookup
    current = current()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail/wagtailadmin/views/home.py", line 71, in render
    }, request=self.request)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 1044, in render
    output = self.filter_expression.resolve(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 711, in resolve
    obj = self.var.resolve(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 852, in resolve
    value = self._resolve_lookup(context)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/template/base.py", line 915, in _resolve_lookup
    current = current()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail/wagtailcore/models.py", line 687, in get_admin_display_title
    return self.title
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/fields.py", line 349, in __get__
    val = getattr(instance, loc_field_name, None)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/models/query_utils.py", line 109, in __get__
    f = [f for f in opts.fields if f.attname == self.field_name][0]
IndexError: list index out of range
```

And the second problem is this:
```
IndexError at /admin/
list index out of range
```

This is his tracebak:
```
Traceback:

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/views/decorators/cache.py" in _cache_controlled
  43.             response = viewfunc(request, *args, **kw)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail/wagtailadmin/decorators.py" in decorated_view
  24.             return view_func(request, *args, **kwargs)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail/wagtailadmin/views/pages.py" in edit
  295.     page = get_object_or_404(Page, id=page_id).get_latest_revision_as_page()

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail/wagtailcore/models.py" in get_latest_revision_as_page
  736.             return latest_revision.as_page_object()

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail/wagtailcore/models.py" in as_page_object
  1447.         obj = self.page.specific_class.from_json(self.content_json)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modelcluster/models.py" in from_json
  278.         return cls.from_serializable_data(json.loads(json_data), check_fks=check_fks, strict_fks=strict_fks)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modelcluster/models.py" in from_serializable_data
  245.         obj = model_from_serializable_data(cls, data, check_fks=check_fks, strict_fks=strict_fks)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modelcluster/models.py" in model_from_serializable_data
  115.     obj = model(**kwargs)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/translator.py" in new_init
  245.         old_init(self, *args, **kwargs)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/wagtail/wagtailcore/models.py" in __init__
  408.         super(Page, self).__init__(*args, **kwargs)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modelcluster/models.py" in __init__
  177.             super(ClusterableModel, self).__init__(*args, **kwargs)

File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/db/models/base.py" in __init__
  555.                 raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])

Exception Type: TypeError at /admin/pages/5/edit/
Exception Value: 'title_es' is an invalid keyword argument for this function
```

I remembered that we have to do some steps more if we are working with a previous project, and yes, here is the information (http://django-modeltranslation.readthedocs.io/en/latest/commands.html#the-update-translation-fields-command). So, i proceeded to use the command, and i have other problem also:
```
 ./manage.py update_translation_fields                                                                              Using default language: es
Updating data of model '<class 'wagtail.wagtailcore.models.Page'>'
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.6/site-packages/modeltranslation/management/commands/update_translation_fields.py", line 32, in handle
    model._default_manager.filter(q).rewrite(False).update(
AttributeError: 'PageQuerySet' object has no attribute 'rewrite'
```

Why? I don't know, i ensured to me that i put all settings right and i added some other for security:
```
MODELTRANSLATION_DEFAULT_LANGUAGE = 'es'
MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'es'
```

And i put the command again, same error.

So, which is the problem here? Which is the solution? Thank you!

**Comment by skirsdeda** [comment]
Did you follow all installation instructions? Did you add TranslationOptions for Page models? Did you run migrations?

**Comment by skirsdeda** [comment]
Also check what Django version you are using.

**Comment by SalahAdDin** [comment]
Yes, i did all two times, my `django` version is `1.10`

**Comment by skirsdeda** [comment]
AFAIK, `django-modeltranslation` doesn't work with `1.10`. See https://github.com/deschler/django-modeltranslation/issues/389.
Try with 1.9 if it's possible.

**Comment by denning** [comment]
Came across this issue because I was having a similar problem but with Mezzanine and django-modeltranslation. 

This commit fixed the problem for me: https://github.com/akiyoko/mezzanine/commit/28aec5e27ae6e77fb7982a8b15dd09b2dcd213cf

**Comment by SalahAdDin** [comment]
@skirsdeda Where will we have `1.10` version?

**Comment by skirsdeda** [comment]
@SalahAdDin Maybe it's best to do additional patching for manager at this point (as @denning suggests) since django-modeltranslation bug isn't being solved for a long time now. I'll have to look into that.

**Comment by SalahAdDin** [comment]
@skirsdeda But are they still continue development these package?

**Comment by skirsdeda** [comment]
@SalahAdDin Finally got some time to fix this. Using the same workaround as mentioned in django-modeltranslation issue. So it works just fine now.

**Comment by SalahAdDin** [comment]
In which issue?

**Comment by skirsdeda** [comment]
deschler/django-modeltranslation#389
